### ISSUE TITLE
xlogdump for PostgreSQL 9.3

### ISSUE THREAD

**Issue by meketen** [snaga/xlogdump#31]
Sorry Japanese Only...

日本語で失礼いたします。
xlogdumpですが、PostgreSQL 9.3への対応予定はありますでしょうか。

**Comment by snaga** [comment]
xlogdumpは9.3から本体で準備されるようになりました。

http://www.postgresql.jp/document/9.3/html/pgxlogdump.html

そちらを試してみていただけますでしょうか。

**Comment by meketen** [comment]
大変失礼致しました。。問題無く利用する事が出来ました。
コメントありがとうございました。
